// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEqTr8XdSu-oKOlsq89xYZpBcjq35el5A',
    appId: '1:971844482482:web:67a3cba566d4ee3ee760ab',
    messagingSenderId: '971844482482',
    projectId: 'asyconf-2307b',
    authDomain: 'asyconf-2307b.firebaseapp.com',
    storageBucket: 'asyconf-2307b.firebasestorage.app',
    measurementId: 'G-VZSMQB6LNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ903kJNqKO68an_UqN3DpvqDJLJ6CJog',
    appId: '1:971844482482:android:f69831b72833ac0de760ab',
    messagingSenderId: '971844482482',
    projectId: 'asyconf-2307b',
    storageBucket: 'asyconf-2307b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHA2WsWjUPtFd9K6fRj2VZ9yk_trmdNFU',
    appId: '1:971844482482:ios:e7b4b47b47455245e760ab',
    messagingSenderId: '971844482482',
    projectId: 'asyconf-2307b',
    storageBucket: 'asyconf-2307b.firebasestorage.app',
    iosBundleId: 'com.example.applicationdeconference',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHA2WsWjUPtFd9K6fRj2VZ9yk_trmdNFU',
    appId: '1:971844482482:ios:e7b4b47b47455245e760ab',
    messagingSenderId: '971844482482',
    projectId: 'asyconf-2307b',
    storageBucket: 'asyconf-2307b.firebasestorage.app',
    iosBundleId: 'com.example.applicationdeconference',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEqTr8XdSu-oKOlsq89xYZpBcjq35el5A',
    appId: '1:971844482482:web:89728aa4194e61e6e760ab',
    messagingSenderId: '971844482482',
    projectId: 'asyconf-2307b',
    authDomain: 'asyconf-2307b.firebaseapp.com',
    storageBucket: 'asyconf-2307b.firebasestorage.app',
    measurementId: 'G-RT25JC5J39',
  );

}